version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    volumes:
      - ./public:/rails/public:ro
  app:
    build: .
    volumes:
      - .:/rails
      - gems:/usr/local/bundle
    environment:
      - COMPOSE_PROJECT_NAME
  db:
    image: postgres:10.3
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  gems:
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME:-resume}_dev
