version: '3'
services:
  app:
    build: .
    volumes:
      - .:/resume
      - resume-gems:/usr/local/bundle
    ports:
      - "3000-3099:3000"
    command: bin/rails server
  db:
    image: postgres:10.3
    volumes:
      - resume-db:/var/lib/postgresql/data
  dba:
    image: adminer:4.6
    ports:
      - "8080:8080"
volumes:
  resume-gems:
  resume-db: