version: '3'
services:
  app:
    build: .
    volumes:
      # - .:/resume
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    # Allow debugging in development
    stdin_open: true
    tty: true
    command: bin/rails server
  db:
    image: postgres:10.3
    volumes:
      - db:/var/lib/postgresql/data
  dba:
    image: adminer:4.6
    ports:
      - "8080:8080"
volumes:
  gems:
  db: