version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    volumes:
      - ./public:/rails/public:ro
    depends_on:
      - app
  app:
    build: .
    volumes:
      - .:/rails
      - gems:/usr/local/bundle
    environment:
      - RAILS_ENV
      - RACK_ENV
      - RAILS_LOG_TO_STDOUT
      - SECRET_KEY_BASE
    depends_on:
      - db
    # Allow debugging in development
    stdin_open: true
    tty: true
  db:
    image: postgres:10.3-alpine
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  gems:
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME:-resume}
