version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
  app:
    build: .
    volumes:
      - .:/resume
      - gems:/usr/local/bundle
    # Allow debugging in development
    stdin_open: true
    tty: true
  db:
    image: postgres:10.3
    volumes:
      - db:/var/lib/postgresql/data
  dba:
    image: adminer:4.6
    ports:
      - "8080:8080"
volumes:
  gems:
  db:
