apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:10.3-alpine
        name: db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db

