apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
spec:
  volumeName: db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90M
  storageClassName: standard
  selector:
    matchLabels:
      app: db
