apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:10.3-alpine
        name: db
        ports:
        - containerPort: 5432
