apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: resume_app
        imagePullPolicy: Never
        name: app
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app
          mountPath: /rails
      volumes:
      - name: app
        persistentVolumeClaim:
          claimName: app

