apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
spec:
  volumeName: app
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 90M
  storageClassName: standard
  selector:
    matchLabels:
      app: app

