apiVersion: v1
kind: PersistentVolume
metadata:
  name: app
  labels:
    app: app
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 100M
  storageClassName: standard
  hostPath:
    path: "/Users/pbrocoum/dev/resume"

