development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: resume_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: resume_production
