development:
  adapter: async
  url: redis://localhost:6379/1
  channel_prefix: resume_development

test:
  adapter: async
  url: redis://localhost:6379/1
  channel_prefix: resume_test

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: resume_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: resume_production
