apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: resume_web
        imagePullPolicy: Never
        name: web
        ports:
        - containerPort: 80
